package com.example.piringku.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF0F5238)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFF2D6A4F)
val OnPrimaryContainer = Color(0xFFA8E7C5)
val InversePrimary = Color(0xFF95D4B3)
val PrimaryFixed = Color(0xFFB1F0CE)
val PrimaryFixedDim = Color(0xFF95D4B3)
val OnPrimaryFixed = Color(0xFF002114)
val OnPrimaryFixedVariant = Color(0xFF0E5138)

val Secondary = Color(0xFF9B4500)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFFC8A40)
val OnSecondaryContainer = Color(0xFF672C00)
val SecondaryFixed = Color(0xFFFFDBC9)
val SecondaryFixedDim = Color(0xFFFFB68D)
val OnSecondaryFixed = Color(0xFF331200)
val OnSecondaryFixedVariant = Color(0xFF763300)

val Tertiary = Color(0xFF713638)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFF8D4D4E)
val OnTertiaryContainer = Color(0xFFFFCFCE)
val TertiaryFixed = Color(0xFFFFDAD9)
val TertiaryFixedDim = Color(0xFFFFB3B3)
val OnTertiaryFixed = Color(0xFF390B0E)
val OnTertiaryFixedVariant = Color(0xFF6F3537)

val Error = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF93000A)

val Background = Color(0xFFF8FAF6)
val OnBackground = Color(0xFF191C1A)
val Surface = Color(0xFFF8FAF6)
val OnSurface = Color(0xFF191C1A)
val SurfaceDim = Color(0xFFD8DBD7)
val SurfaceBright = Color(0xFFF8FAF6)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFF2F4F0)
val SurfaceContainer = Color(0xFFECEEEA)
val SurfaceContainerHigh = Color(0xFFE7E9E5)
val SurfaceContainerHighest = Color(0xFFE1E3DF)
val SurfaceVariant = Color(0xFFE1E3DF)
val OnSurfaceVariant = Color(0xFF404943)
val InverseSurface = Color(0xFF2E312F)
val InverseOnSurface = Color(0xFFEFF1ED)
val SurfaceTint = Color(0xFF2C694E)

val Outline = Color(0xFF707973)
val OutlineVariant = Color(0xFFBFC9C1)

val HealthGreen = Color(0xFF40916C)
val EnergyOrange = Color(0xFFFFB385)
val DataBlue = Color(0xFF4361EE)
val ErrorRed = Color(0xFFE63946)
val SurfaceGray = Color(0xFFF8F9FA)
val BorderSubtle = Color(0xFFE9ECEF)
